default_install_hook_types: [pre-commit, prepare-commit-msg, post-commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]  # this project names tests test_*.py
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: prepare-ai-repository
        name: Prepare repository for AI prompt recording
        language: script
        entry: .venv/bin/prepare-ai-repository
        stages: [manual]
        always_run: true

      - id: unstage-ai-prompts
        name: Unstage AI prompts
        language: script
        entry: .venv/bin/unstage-ai-prompts
        stages: [pre-commit]
        always_run: true

      - id: append-ai-prompts
        name: Append AI prompts to commit message
        language: script
        entry: .venv/bin/append-ai-prompts
        stages: [prepare-commit-msg]
        always_run: true

      - id: archive-ai-prompts
        name: Archive AI prompts
        language: script
        entry: .venv/bin/archive-ai-prompts
        stages: [post-commit]
        always_run: true
