name: Tests

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and test dependencies
        run: make dev

      - name: Run tests
        run: make test

  deploy-github-release:
    # only deploy on tags, see https://stackoverflow.com/a/58478262/1320237
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Create GitHub release from tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: "To view the changes, please refer to the [Changelog](https://github.com/pycalendar/ai-prompt-auto-commit/blob/main/CHANGES.md)."
          generateReleaseNotes: false
